[project]
name = "olx-price-monitor-bot"
version = "0.1.0"
description = "A telegram bot to monitor prices on olx.kz"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiogram>=3.30.0",
    "aiosqlite>=0.22.1",
    "playwright>=1.61.0",
    "playwright-stealth>=2.0.3",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.0",
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
start = "uv run --env-file .env main.py"
