[project]
name = "olx-monitor-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.30.0",
    "aiosqlite>=0.22.1",
    "dotenv>=0.9.9",
    "playwright>=1.61.0",
    "playwright-stealth>=2.0.3",
]

[dependency-groups]
dev = [
    "ruff>=0.16.0",
]
